version: "3.8"
services:
 client:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
       OVERRIDE_SEMESTER: ${OVERRIDE_SEMESTER}
       SEMESTER: ${SEMESTER}
   ports:
     - "8084:8080"
   image: campusservices/idworks
   container_name: idworkscontainer
   tty: true