version: "3.8"
services:
 client:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
       ENV_OVERRIDE_SEMESTER: ${ENV_OVERRIDE_SEMESTER}
       ENV_SEMESTER: ${ENV_SEMESTER}
   ports:
     - "8084:8080"
   image: campusservices/idworks
   container_name: idworkscontainer
   restart: always